use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

fn scan_roles_dir() -> BTreeMap<String, Vec<String>> {
    let roles_dir = Path::new("resources/roles");
    let mut result: BTreeMap<String, Vec<String>> = BTreeMap::new();

    if !roles_dir.exists() {
        return result;
    }

    let entries = fs::read_dir(roles_dir).expect("Failed to read resources/roles directory");
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let dept_name = path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();

        if dept_name == "catalog.json" {
            continue;
        }

        let mut json_files: Vec<String> = Vec::new();
        scan_json_files_recursive(&path, &mut json_files, &dept_name);
        if !json_files.is_empty() {
            result.insert(dept_name, json_files);
        }
    }

    result
}

fn scan_json_files_recursive(dir: &Path, files: &mut Vec<String>, dept: &str) {
    let entries = fs::read_dir(dir).expect("Failed to read directory");
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let sub_name = path.file_name().unwrap_or_default().to_string_lossy();
            scan_json_files_recursive(&path, files, &format!("{}/{}", dept, sub_name));
            continue;
        }
        if path.extension().map_or(false, |e| e == "json") {
            let file_name = path.file_name().unwrap_or_default().to_string_lossy();
            files.push(format!("{}/{}", dept, file_name));
        }
    }
}

fn main() {
    let git_dir = std::path::Path::new("hermes-agent-source/.git");
    let backup = std::path::Path::new(".git.hermes-agent.backup");
    let needs_restore = git_dir.exists() && !backup.exists();
    if needs_restore {
        std::fs::rename(git_dir, backup).ok();
    }

    let roles_map = scan_roles_dir();
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("builtin_roles_manifest.rs");

    let mut code = String::new();
    code.push_str("/// Auto-generated by build.rs - DO NOT EDIT\n\n");
    code.push_str("pub fn load_all_builtin_roles() -> Vec<crate::database::seeds::RoleSeed> {\n");
    code.push_str("    let mut roles = Vec::new();\n");

    for (_dept, files) in &roles_map {
        for file_path in files {
            code.push_str(&format!(
                "    roles.push(serde_json::from_str::<crate::database::seeds::RoleSeed>(include_str!(\"../../../../../resources/roles/{}\")).expect(\"Failed to parse {}\"));\n",
                file_path, file_path
            ));
        }
    }

    code.push_str("    roles\n}\n\n");

    code.push_str("pub fn builtin_role_departments() -> Vec<(&'static str, usize)> {\n");
    code.push_str("    let mut depts = Vec::new();\n");
    for (dept, files) in &roles_map {
        code.push_str(&format!(
            "    depts.push((\"{}\", {}usize));\n",
            dept,
            files.len()
        ));
    }
    code.push_str("    depts\n}\n");

    fs::write(&dest_path, code).expect("Failed to write builtin_roles_manifest.rs");

    tauri_build::build();

    if needs_restore {
        std::fs::rename(backup, git_dir).ok();
    }
}
