/**
 * 共享 mock 数据 fixtures
 */
export const fixtures = {
  project: {
    id: "proj-1",
    name: "Test Project",
    description: "A test project",
    icon: "📁",
    projectRule: "test-rule",
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  project2: {
    id: "proj-2",
    name: "Another Project",
    description: "Second project",
    icon: "🚀",
    projectRule: "rule-2",
    isFavorite: true,
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 3600000,
  },
  aiRole: {
    id: "role-1",
    name: "Frontend Developer",
    nickname: "Frontend",
    icon: "💻",
    description: "Builds UI",
    responsibilities: "Write code",
    soulContent: "Be a great frontend engineer",
    avatarType: "default",
    avatarColor: "#6c5ce7",
  },
  conversation: {
    id: "conv-1",
    title: "Chat about React",
    status: "active" as const,
    lastActiveAt: Date.now(),
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  message: {
    id: "msg-1",
    role: "user" as const,
    content: "Hello world",
    timestamp: 1000,
  },
  knowledgeBase: {
    id: "kb-1",
    name: "Test KB",
    icon: "📚",
    status: "ready" as const,
    description: "A test knowledge base",
    fileCount: 0,
    createdAt: Date.now(),
  },
  provider: {
    id: "p1",
    name: "OpenAI",
    value: "openai",
    baseUrl: "https://api.openai.com/v1",
    apiKey: "sk-test",
    apiKeyEnv: "OPENAI_API_KEY",
  },
  projectMember: {
    id: "member-1",
    projectId: "proj-1",
    roleId: "role-1",
    status: "active",
    isWorking: false,
  },
  projectWorkflow: {
    id: "wf-1",
    projectId: "proj-1",
    fromRoleId: "role-1",
    toRoleId: "role-2",
    artifactType: "code",
    transitionType: "auto_push" as const,
  },
  projectArtifact: {
    id: "artifact-1",
    projectId: "proj-1",
    roleId: "role-1",
    artifactType: "code",
    title: "Test Artifact",
    filePath: "/tmp/test.txt",
    content: "Hello",
    status: "pending" as const,
  },
  projectTask: {
    id: "task-1",
    projectId: "proj-1",
    title: "Test Task",
    description: "Do something",
    status: "pending" as const,
    priority: "medium" as const,
    assigneeId: "role-1",
    createdAt: Date.now(),
  },
};
